/** Canonical AFM.ai analytics event types (telemetry contract). */
export const AnalyticsEventType = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  PAGE_OPEN: "PAGE_OPEN",
  PAGE_CLOSE: "PAGE_CLOSE",
  PAGE_VIEW: "PAGE_VIEW",
  CLICK: "CLICK",
  KEYBOARD: "KEYBOARD",
  MOUSE_MOVE: "MOUSE_MOVE",
  SCROLL: "SCROLL",
  TAB_ACTIVE: "TAB_ACTIVE",
  TAB_INACTIVE: "TAB_INACTIVE",
  BROWSER_MINIMIZED: "BROWSER_MINIMIZED",
  BROWSER_VISIBLE: "BROWSER_VISIBLE",
  SESSION_START: "SESSION_START",
  SESSION_END: "SESSION_END",
  SESSION_HEARTBEAT: "SESSION_HEARTBEAT",
  IDLE_START: "IDLE_START",
  IDLE_END: "IDLE_END",
  AI_REQUEST: "AI_REQUEST",
  AI_RESPONSE: "AI_RESPONSE",
  AI_STREAM_START: "AI_STREAM_START",
  AI_STREAM_END: "AI_STREAM_END",
  VIDEO_RENDER_START: "VIDEO_RENDER_START",
  VIDEO_RENDER_COMPLETE: "VIDEO_RENDER_COMPLETE",
  IMAGE_GENERATION_START: "IMAGE_GENERATION_START",
  IMAGE_GENERATION_COMPLETE: "IMAGE_GENERATION_COMPLETE",
  WORKFLOW_START: "WORKFLOW_START",
  WORKFLOW_COMPLETE: "WORKFLOW_COMPLETE",
  AGENT_EXECUTION: "AGENT_EXECUTION",
  RESEARCH_SESSION: "RESEARCH_SESSION",
  WEBSOCKET_CONNECT: "WEBSOCKET_CONNECT",
  WEBSOCKET_DISCONNECT: "WEBSOCKET_DISCONNECT",
  WEBSOCKET_RECONNECT: "WEBSOCKET_RECONNECT",
  UPLOAD_START: "UPLOAD_START",
  UPLOAD_COMPLETE: "UPLOAD_COMPLETE",
  ERROR_EVENT: "ERROR_EVENT",
  API_FAILURE: "API_FAILURE",
  BACKGROUND_TASK: "BACKGROUND_TASK",
} as const;

export type AnalyticsEventTypeName =
  (typeof AnalyticsEventType)[keyof typeof AnalyticsEventType];

export const TimeMetricKind = {
  SESSION_TOTAL: "session_total",
  ACTIVE_USAGE: "active_usage",
  IDLE: "idle",
  AI_INTERACTION: "ai_interaction",
  PAGE_VIEW: "page_view",
  WORKFLOW: "workflow",
  AI_GENERATION: "ai_generation",
  VIDEO_RENDER: "video_render",
  IMAGE_GENERATION: "image_generation",
  RESEARCH: "research",
  WEBSOCKET: "websocket",
  WORKSPACE: "workspace",
  AGENT_EXECUTION: "agent_execution",
  BACKGROUND_TASK: "background_task",
} as const;

export type TimeMetricKindName =
  (typeof TimeMetricKind)[keyof typeof TimeMetricKind];
