import { orchestrateChat } from "@/lib/ai/orchestrator";

export type WebsiteStack = {
  frontend: string;
  backend: string;
  database: string;
  css: string;
};

export interface WebsiteBuildResult {
  prompt: string;
  stack: WebsiteStack;
  files: Array<{ path: string; content: string }>;
  readme: string;
  deployNotes: string;
}

/** Coerce API/client payloads so deploy validation never fails on missing stack fields. */
export function normalizeWebsiteProject(
  raw: Partial<WebsiteBuildResult> | null | undefined
): WebsiteBuildResult {
  const stackIn = raw?.stack ?? {};
  return {
    prompt: typeof raw?.prompt === "string" ? raw.prompt : "",
    stack: {
      frontend: stackIn.frontend ?? DEFAULT_STACK.frontend,
      backend: stackIn.backend ?? DEFAULT_STACK.backend,
      database: stackIn.database ?? DEFAULT_STACK.database,
      css: stackIn.css ?? DEFAULT_STACK.css,
    },
    files: Array.isArray(raw?.files)
      ? raw.files.map((f) => ({
          path: String(f?.path ?? "unknown"),
          content: String(f?.content ?? ""),
        }))
      : [],
    readme:
      typeof raw?.readme === "string"
        ? raw.readme
        : "# Project\n\nGenerated by AFM.ai Website Builder.",
    deployNotes:
      typeof raw?.deployNotes === "string"
        ? raw.deployNotes
        : "Deploy: push to GitHub → import in Vercel → set DATABASE_URL and auth env vars.",
  };
}

const DEFAULT_STACK: WebsiteStack = {
  frontend: "Next.js 15 (App Router)",
  backend: "Next.js API Routes",
  database: "PostgreSQL + Prisma",
  css: "Tailwind CSS + shadcn/ui",
};

export async function generateWebsiteProject(params: {
  prompt: string;
  stack?: Partial<WebsiteStack>;
}): Promise<WebsiteBuildResult> {
  const stack = { ...DEFAULT_STACK, ...params.stack };
  const result = await orchestrateChat({
    messages: [
      {
        role: "user",
        content: `You are a senior full-stack engineer. Build a complete website project for this request:

"${params.prompt}"

Stack: ${stack.frontend}, ${stack.backend}, ${stack.database}, ${stack.css}.

Respond with EXACTLY this structure (no extra prose before FILE blocks):

README:
(setup, env vars, deploy to Vercel)

FILE: package.json
\`\`\`json
...
\`\`\`

FILE: app/page.tsx
\`\`\`tsx
...
\`\`\`

FILE: app/layout.tsx
\`\`\`tsx
...
\`\`\`

FILE: app/globals.css
\`\`\`css
...
\`\`\`

FILE: prisma/schema.prisma
\`\`\`prisma
...
\`\`\`

FILE: .env.example
\`\`\`
...
\`\`\`

Include auth-ready structure, responsive UI, SEO metadata, and at least 4 pages or sections.`,
      },
    ],
    modelSelection: "auto",
  });

  const files = parseGeneratedFiles(result.reply);
  const readme =
    files.find((f) => f.path === "README.md")?.content ??
    extractSection(result.reply, "README:") ??
    "# Project\n\nGenerated by AFM.ai Website Builder.";

  return normalizeWebsiteProject({
    prompt: params.prompt,
    stack,
    files,
    readme,
    deployNotes:
      "Deploy: push to GitHub → import in Vercel → set DATABASE_URL and auth env vars.",
  });
}

function parseGeneratedFiles(text: string): Array<{ path: string; content: string }> {
  const files: Array<{ path: string; content: string }> = [];
  const re = /FILE:\s*([^\n]+)\n```[\w]*\n([\s\S]*?)```/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text)) !== null) {
    files.push({ path: m[1].trim(), content: m[2].trim() });
  }
  if (!files.length && text.length > 100) {
    files.push({ path: "app/page.tsx", content: text.slice(0, 12000) });
  }
  return files;
}

function extractSection(text: string, header: string): string | null {
  const idx = text.indexOf(header);
  if (idx < 0) return null;
  const rest = text.slice(idx + header.length);
  const end = rest.search(/\nFILE:/);
  return (end >= 0 ? rest.slice(0, end) : rest).trim();
}
